# Generated by Django 5.2.11 on 2026-04-19 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0003_student_github_student_linkedin_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='experience',
            field=models.CharField(default='Fresher', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='job_type',
            field=models.CharField(default='Full-Time', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='work_mode',
            field=models.CharField(default='On-Site', max_length=50),
        ),
    ]
